version: '3.1'

services:
  db:
    image: mongo
    restart: always
  http:
    image: docker.io/library/linky:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS=-Dspring.data.mongodb.uri=mongodb://db/test
